name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 手动触发事件
  workflow_dispatch:
    inputs:
      tags:
        description: 'update source image'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3 # v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Aliyun
        uses: docker/login-action@v3 # v3.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6.3.0
        with:
          file: ./texlive-zh/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            laotie255/texlive-zh:latest
            registry.cn-hangzhou.aliyuncs.com/laotie255/texlive-zh:latest
